[project]
name = "climatebenchpress.data_loader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cf-xarray~=0.10",
    "cftime~=1.6",
    "dask~=2024.12",
    "fsspec~=2024.12",
    "universal-pathlib~=0.2",
    "xarray~=2025.1",
    "zarr~=2.18",
]

[dependency-groups]
dev = ["ipykernel~=6.29", "mypy~=1.14", "pandas-stubs~=2.2", "ruff~=0.8"]
data = ["gcsfs~=2024.12", "pandas~=2.2"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"climatebenchpress.compressor" = ["py.typed"]

[[tool.mypy.overrides]]
module = ["fsspec.*", "zarr.*"]
follow_untyped_imports = true
